# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
movies = Movie.create ([{ name: 'Looper', category: "action" }, { name: 'Star Wars' }, { name: 'Blade Runner' }, { name: 'Guardians of the Galaxy' }, { name: 'Edge of Tomorrow' }, { name: 'Avatar' }, { name: 'Terminator' }, { name: 'Elysium' }, { name: 'Men In Black' }, { name: 'Passengers' }, { name: 'The Host' }, { name: 'Galaxy Quest' },{ name: 'Wall-e' }, { name: 'The Martian' }, { name: 'Gattaca' }, { name: 'Arrival' }, { name: 'Star Trek: The Wrath of Khan' }, { name: 'Gravity' }, { name: 'Akira' }, { name: 'Hitchhiker\'s Guide to the Galaxy' }, { name: 'Prometheus' }, { name: 'AI' }, { name: 'Ad Astra' }, { name: 'Alien' }, { name: 'The Thing' }, { name: 'Monsters vs Aliens' }, { name: 'The Iron Giant' }, { name: '9' }, { name: 'Final Fantasy: The Spirits Within' }, { name: 'Treasure Planet' }])


books = Book.create ([{ name: 'Red Rising' }, { name: 'Snow Crash' }, { name: 'Ender\'s Game'}, { name: 'Starship Troopers' }, { name: 'Consider Phlebas' }, { name: 'Fortune\'s Pawn' }, { name: 'Dune' }, { name: 'Neuromancer' }, { name: 'Shards of Honor' }, { name: 'Grimspace' }, { name: 'Overload Flux' }, { name: 'Shadowrun: Choose Your Enemies Carefully' }, { name: 'The Left Hand of Darkness' }, { name: 'Do Androids Dream of Electric Sleep?' }, { name: 'The Paradox Men' }, { name: '1984' }, { name: 'The Giver' }, { name: 'Hyperion' }, { name: 'I Am Legend' }, { name: 'Year Zero' }, { name: 'Redshirts' }, { name: 'World War Z' }, { name: 'Blindsight' }, { name: 'Altered Carbon' }, { name: 'Fahrenheit 451' }, { name: 'Revelation Space' }, { name: 'Illuminae Files' }])

shows = Show.create ([{ name: 'Fringe' }, { name: 'Farscape' }, { name: 'Star Trek' }, { name: 'Haven' }, { name: 'Voltron' }, { name: 'Final Space' }, { name: 'Futurama' }, { name: 'Farscape' }, { name: 'Firefly' }, { name: 'The Orville' }, { name: 'Rick and Morty' }, { name: 'The X-Files' }, { name: 'Westworld' }, { name: 'Supernatural' }, { name: 'Ghost in the Shell' }, { name: 'Altered Carbon' }, { name: 'The Expanse' }, { name: 'Orphan Black' }, { name: 'The Twilight Zone' }, { name: 'Star Wars: The Clone Wars' }, { name: 'Generator Rex' }, { name: 'The Mandalorian' }, { name: 'Heroes' }, { name: 'Channel Zero' }, { name: 'Black Mirror' }, { name: 'The Venture Bros.' }])

games = Game.create ([{ name: 'Cyberpunk 2077' }, { name: 'Half-Life' }, { name: 'Bioshock' }, { name: 'Deus Ex' }, { name: 'Prey' }, { name: 'Halo' },{ name: 'Titanfall' }, { name: 'Mass Effect' }, { name: 'Metroid Prime' }, { name: 'Shadowrun Returns' }, { name: 'NieR: Automata' }, { name: 'No Man\'s Sky' }, { name: 'Star Wars: Knights of the Republic' }, { name: 'Tacoma' }, { name: 'Xenoblade Chronicles' }, { name: 'Alien Isolation' }, { name: 'System Shock' }, { name: 'Dead Space' }, { name: 'The Station' }, { name: 'Orwell' }, { name: 'Detroit: Become Human' }, { name: 'Event 0' }, { name: 'The Outer Worlds' }, { name: 'The Stanley Parable' }, { name: 'Kerbal Space Program' }])